const fs = require('fs');
const env = require('dotenv').config({path: '../flashpay/.env'}).parsed;
const key = env.SUPABASE_KEY;
const url = env.SUPABASE_URL;

let html = fs.readFileSync('index.html', 'utf8');

const supabase = [
  'const SUPABASE_URL="' + url + '";',
  'const SUPABASE_KEY="' + key + '";',
  'const ADMIN_PASSWORD="flashpay2026admin";',
  'let isAdminAuthenticated=false;',
  'let applications=[];',
  '',
  'async function supabaseRequest(method,endpoint,body){',
  '  const options={method,headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY,"Authorization":"Bearer "+SUPABASE_KEY,"Prefer":"return=minimal"}};',
  '  if(body)options.body=JSON.stringify(body);',
  '  const res=await fetch(SUPABASE_URL+"/rest/v1/"+endpoint,options);',
  '  if(method==="POST")return res.ok;',
  '  return res.json();',
  '}',
  '',
  'async function fetchApplications(){',
  '  try{const data=await supabaseRequest("GET","job_applications?order=created_at.desc&select=*");',
  '  applications=data||[];renderApplications();updateAdminStats();}catch(e){}',
  '}',
  '',
  'function updateAdminStats(){',
  '  document.getElementById("totalApps").textContent=applications.length;',
  '  document.getElementById("newApps").textContent=applications.filter(a=>a.status==="new").length;',
  '  document.getElementById("approvedApps").textContent=applications.filter(a=>a.status==="approved").length;',
  '  document.getElementById("rejectedApps").textContent=applications.filter(a=>a.status==="rejected").length;',
  '}',
  '',
  'function adminLogin(){',
  '  const p=prompt("Enter admin password:");',
  '  if(p===ADMIN_PASSWORD){isAdminAuthenticated=true;fetchApplications();showToast("Admin access granted!");}',
  '  else showToast("Incorrect password!");',
  '}',
  '',
  'function renderApplications(){',
  '  const tbody=document.getElementById("applicationsTable");',
  '  if(!isAdminAuthenticated){',
  '    tbody.innerHTML="<tr><td colspan=7 style=\'text-align:center;padding:40px\'><p style=\'color:#aaa;margin-bottom:12px\'>Admin access required</p><button onclick=\'adminLogin()\' style=\'background:#C8972A;color:#1A3C2E;border:none;padding:10px 24px;border-radius:100px;font-weight:700;cursor:pointer\'>Login as Admin</button></td></tr>";',
  '    updateAdminStats();return;',
  '  }',
  '  if(!applications.length){',
  '    tbody.innerHTML="<tr><td colspan=7 style=\'text-align:center;color:#aaa;padding:40px\'>No applications yet.</td></tr>";',
  '    updateAdminStats();return;',
  '  }',
  '  tbody.innerHTML=applications.map((a,i)=>"<tr><td>"+(i+1)+"</td><td><strong>"+a.full_name+"</strong><br><small>"+a.email+"</small></td><td>"+a.role+"</td><td>"+a.experience+"</td><td>"+new Date(a.created_at).toLocaleDateString()+"</td><td><span class=\'status-badge status-"+a.status+"\'>" +a.status+"</span></td><td><button class=\'action-btn btn-view\' onclick=\'viewApp("+i+")\'>View</button> <button class=\'action-btn btn-approve\' onclick=\'updateAppStatus("+JSON.stringify(a.id)+",\\\'approved\\\')\'>✓</button> <button class=\'action-btn btn-reject\' onclick=\'updateAppStatus("+JSON.stringify(a.id)+",\\\'rejected\\\')\'>✗</button></td></tr>").join("");',
  '  updateAdminStats();',
  '}',
  '',
  'async function updateAppStatus(id,status){',
  '  await supabaseRequest("PATCH","job_applications?id=eq."+id,{status});',
  '  fetchApplications();showToast("Status updated!");',
  '}',
  '',
  'function viewApp(i){',
  '  const a=applications[i];',
  '  alert("Name: "+a.full_name+"\\nEmail: "+a.email+"\\nPhone: "+a.phone+"\\nRole: "+a.role+"\\nExperience: "+a.experience+"\\nSkills: "+a.skills+"\\nPortfolio: "+(a.portfolio||"N/A")+"\\n\\nMotivation:\\n"+a.motivation);',
  '}',
  '',
  'async function submitApplication(e){',
  '  e.preventDefault();',
  '  const btn=document.querySelector(".submit-btn");',
  '  btn.textContent="Submitting...";btn.disabled=true;',
  '  const app={',
  '    full_name:document.getElementById("fullName").value,',
  '    email:document.getElementById("email").value,',
  '    phone:document.getElementById("phone").value,',
  '    role:document.getElementById("role").value,',
  '    skills:document.getElementById("skills").value,',
  '    experience:document.getElementById("experience").value,',
  '    portfolio:document.getElementById("portfolio").value,',
  '    motivation:document.getElementById("motivation").value,',
  '    status:"new"',
  '  };',
  '  try{',
  '    const ok=await supabaseRequest("POST","job_applications",app);',
  '    if(ok){document.getElementById("applicationForm").reset();document.getElementById("fileLabel").textContent="Click to upload your CV";showToast("Application submitted! We will be in touch within 5 working days.");if(isAdminAuthenticated)fetchApplications();}',
  '    else showToast("Submission failed. Try again.");',
  '  }catch(err){showToast("Submission failed. Try again.");}',
  '  btn.textContent="Submit Application";btn.disabled=false;',
  '}',
  '',
  'function showToast(msg){',
  '  const t=document.getElementById("toast");',
  '  t.textContent=msg;t.classList.add("show");',
  '  setTimeout(()=>t.classList.remove("show"),4000);',
  '}',
  '',
  'renderApplications();',
  'updateAdminStats();',
].join('\n');

const scriptStart = html.lastIndexOf('<script>');
const scriptEnd = html.lastIndexOf('</script>');
const oldScript = html.substring(scriptStart + 8, scriptEnd);

html = html.replace(oldScript, '\n' + supabase + '\n');
fs.writeFileSync('index.html', html);
console.log('Done! Size:', html.length);
